/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package taller.pkg1.java;

import javax.swing.JOptionPane;

/**
 *
 * @author MC
 */
public class panel1 extends javax.swing.JFrame {
    
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(panel1.class.getName());

    /**
     * Creates new form panel1
     */
    int contadorIntentos = 0;
    public panel1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        usertext = new javax.swing.JLabel();
        contratext = new javax.swing.JLabel();
        iniciarsesion = new javax.swing.JButton();
        usuario = new javax.swing.JTextField();
        contrasena = new javax.swing.JPasswordField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel1.setText("Inicia sesión en tu cuenta.");

        usertext.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        usertext.setText("Usuario/ Email");

        contratext.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        contratext.setText("Contraseña");

        iniciarsesion.setBackground(new java.awt.Color(255, 102, 0));
        iniciarsesion.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        iniciarsesion.setForeground(new java.awt.Color(255, 255, 255));
        iniciarsesion.setText("Iniciar sesión");
        iniciarsesion.addActionListener(this::iniciarsesionActionPerformed);
        iniciarsesion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                iniciarsesionKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(usuario)
                        .addComponent(contratext)
                        .addComponent(iniciarsesion, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                        .addComponent(contrasena))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(usertext)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usertext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contratext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(iniciarsesion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarsesionActionPerformed
    
    String textoUsuario = usuario.getText(); 
    String textoPassword = new String(contrasena.getPassword()); 
    
    
    if ((textoUsuario.equals("Cantorin") && textoPassword.equals("1234")) || 
        (textoUsuario.equals("cantorin@tupa.com") && textoPassword.equals("1234"))) {

        JOptionPane.showMessageDialog(this, "¡Bienvenido al sistema!");

        panel2 g = new panel2();
        g.setVisible(true);
        g.setLocationRelativeTo(null);
        g.setTitle("Veterinaria Rayo.pe"); 
        
        this.dispose();
        
    } else {
        
        contadorIntentos++;
        
        if (contadorIntentos >= 3) {
            JOptionPane.showMessageDialog(this, "Máximo de intentos alcanzado. Sistema bloqueado.");

            iniciarsesion.setEnabled(false); 
            usuario.setEnabled(false);
            contrasena.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, "Credenciales incorrectas. Intento " + contadorIntentos + " de 3.");
        }
    }

    }//GEN-LAST:event_iniciarsesionActionPerformed

    private void iniciarsesionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_iniciarsesionKeyPressed
   
    }//GEN-LAST:event_iniciarsesionKeyPressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new panel1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField contrasena;
    private javax.swing.JLabel contratext;
    private javax.swing.JButton iniciarsesion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel usertext;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
