/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package taller.pkg1.java;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author MC
 */
public class panel2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(panel2.class.getName());

    /**
     * Creates new form panel2
     */
    ArrayList<String> listaMascotas = new ArrayList<>();
    public panel2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        nom = new javax.swing.JLabel();
        esp = new javax.swing.JLabel();
        raz = new javax.swing.JLabel();
        edad = new javax.swing.JLabel();
        peso = new javax.swing.JLabel();
        col = new javax.swing.JLabel();
        sex = new javax.swing.JLabel();
        n1 = new javax.swing.JTextField();
        n2 = new javax.swing.JTextField();
        n3 = new javax.swing.JTextField();
        n4 = new javax.swing.JTextField();
        n5 = new javax.swing.JTextField();
        n6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        nuevo = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        hembra = new javax.swing.JRadioButton();
        macho = new javax.swing.JRadioButton();
        registros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nom.setText("Nombre");

        esp.setText("Especie");

        raz.setText("Raza");

        edad.setText("Edad");

        peso.setText("Peso");

        col.setText("Color");

        sex.setText("Sexo");

        n1.addActionListener(this::n1ActionPerformed);

        n6.addActionListener(this::n6ActionPerformed);

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setText("Aceptar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        nuevo.setBackground(new java.awt.Color(2, 125, 222));
        nuevo.setText("Nuevo");
        nuevo.addActionListener(this::nuevoActionPerformed);

        jButton3.setBackground(new java.awt.Color(253, 1, 1));
        jButton3.setText("Salir");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jLabel8.setBackground(new java.awt.Color(153, 204, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("INGRESAR DATOS DE LA MASCOTA");

        buttonGroup1.add(hembra);
        hembra.setText("Hembra");

        buttonGroup1.add(macho);
        macho.setText("Macho");
        macho.addActionListener(this::machoActionPerformed);

        registros.setBackground(new java.awt.Color(255, 255, 0));
        registros.setText("Registros");
        registros.addActionListener(this::registrosActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(registros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nuevo)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nom)
                            .addComponent(esp)
                            .addComponent(raz)
                            .addComponent(edad)
                            .addComponent(peso)
                            .addComponent(col)
                            .addComponent(sex))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(n1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                            .addComponent(n2)
                            .addComponent(n3)
                            .addComponent(n4)
                            .addComponent(n5)
                            .addComponent(n6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hembra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(macho)))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nom)
                    .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(esp)
                    .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(raz)
                    .addComponent(n3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edad)
                    .addComponent(n4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peso)
                    .addComponent(n5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(col)
                    .addComponent(n6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sex)
                    .addComponent(hembra)
                    .addComponent(macho))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(nuevo)
                    .addComponent(jButton3)
                    .addComponent(registros))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
int valor = JOptionPane.showConfirmDialog(this, "¿Estás segura/o de salir del sistema?", "Terminar", JOptionPane.YES_NO_OPTION);
    
     if (valor== JOptionPane.YES_OPTION)
     {
         JOptionPane.showMessageDialog(null, "Hasta la vista baby 😎", "Salida", JOptionPane.INFORMATION_MESSAGE);
          System.exit(0);
     }        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
    String textoNombre = n1.getText();
    String textoEspecie = n2.getText();
    String textoRaza = n3.getText();
    String textoEdad = n4.getText();
    String textoPeso = n5.getText();
    String textoColor = n6.getText();
    String textoSexo = "No especificado"; 
    if (hembra.isSelected()) {
        textoSexo = "Hembra";
    } else if (macho.isSelected()) {
        textoSexo = "Macho";
    }

    
    if (textoNombre.isEmpty() || textoEspecie.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, ingresa al menos el Nombre y la Especie.");
    } else {
        
        String datosMascota = textoNombre + " | " + textoEspecie + " | " + textoRaza + " | " + textoEdad + " | " + textoPeso + " | " + textoColor + " | " + textoSexo;
        
        
        listaMascotas.add(datosMascota);
        
        
        JOptionPane.showMessageDialog(this, "Mascota guardada con éxito\nTotal registradas: " + listaMascotas.size());
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
    
    n1.setText(null);
    n2.setText(null);
    n3.setText(null);
    n4.setText(null);
    n5.setText(null);
    n6.setText(null);
    buttonGroup1.clearSelection();
    nuevo.requestFocus();
    }//GEN-LAST:event_nuevoActionPerformed

    private void machoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_machoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_machoActionPerformed

    private void n6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n6ActionPerformed

    private void registrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrosActionPerformed
                                             
    
    if (listaMascotas.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Aún no hay mascotas en el registro.");
    } else {
      
        panel3 ventanaLista = new panel3();

        ventanaLista.mostrarDatos(listaMascotas);
        ventanaLista.setVisible(true);
        ventanaLista.setLocationRelativeTo(null);
    }

    }//GEN-LAST:event_registrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new panel2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel col;
    private javax.swing.JLabel edad;
    private javax.swing.JLabel esp;
    private javax.swing.JRadioButton hembra;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton macho;
    private javax.swing.JTextField n1;
    private javax.swing.JTextField n2;
    private javax.swing.JTextField n3;
    private javax.swing.JTextField n4;
    private javax.swing.JTextField n5;
    private javax.swing.JTextField n6;
    private javax.swing.JLabel nom;
    private javax.swing.JButton nuevo;
    private javax.swing.JLabel peso;
    private javax.swing.JLabel raz;
    private javax.swing.JButton registros;
    private javax.swing.JLabel sex;
    // End of variables declaration//GEN-END:variables
}
